ERP.UI/Controllers/ClassListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERP.ViewModel;
using ERP.IBLL;

namespace ERP.UI.Controllers
{
    public class ClassListController : Controller
    {
        private IProductClassBLL<ProductClassModel> productClassBLL;

        public ClassListController(IProductClassBLL<ProductClassModel> _productClassBLL)
        {
            this.productClassBLL = _productClassBLL;
        }

        /// <summary>
        /// 下拉框
        /// </summary>
        /// <param name="selectedValue"></param>
        /// <param name="FirstText"></param>
        /// <param name="FirstValue"></param>
        /// <returns></returns>
        public ActionResult Index(int? selectedValue, string FirstText = "做为一级分类", int FirstValue = 0, object config = null)
        {
            //从业务逻辑层获取所有分类（菜单）数据
            List<ProductClassModel> productClassModels = productClassBLL.GetAll();

            //创建下拉项集合（空的）
            List<SelectListItem> items = new List<SelectListItem>();

            //第一个下拉项的默认文本和默认值
            items.Add(new SelectListItem { Text = FirstText, Value = FirstValue.ToString() });

            foreach (var item in productClassModels)
            {
                string nbsp = string.Empty;
                for (int i = 0; i < item.Depth * 4; i++)
                {
                    //HTML空格
                    nbsp += "&nbsp;";
                }

                //添加下拉的菜单项
                //<option value="123" selected="selected">asd</option>
                SelectListItem li = new SelectListItem { Text = Server.HtmlDecode(nbsp + "├" + item.ClassName), Value = item.ClassID.ToString() };

                //设置选中项
                if (item.ClassID == selectedValue)
                {
                    li.Selected = true;
                }

                items.Add(li);
            }

            ViewBag.config = config;

            return View(items);
        }
    }
}

ERP.UI/Controllers/ProductClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERP.ViewModel;
using ERP.IBLL;

namespace ERP.UI.Controllers
{
    public class ProductClassController : Controller
    {
        private IProductClassBLL<ProductClassModel> productClassBLL;

        public ProductClassController(IProductClassBLL<ProductClassModel> _productClassBLL)
        {
            this.productClassBLL = _productClassBLL;
        }

        /// <summary>
        /// 所有的商品分类
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(productClassBLL.GetAll());
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(ProductClassModel Model)
        {
            return Json(productClassBLL.Add(Model), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 获取数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(productClassBLL.GetModel(id));
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(ProductClassModel Model)
        {
            return Json(productClassBLL.Update(Model), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Move(int id)
        {
            IEnumerable<ProductClassModel> productClasses = productClassBLL.GetAll();
            ProductClassModel productClassModel = productClasses.First(m => m.ClassID == id);
            if(productClassModel.ParentID == 0)
            {
                ViewBag.parentClass = "顶级分类";
            }
            else
            {
                ViewBag.parentClass = productClasses.First(m => m.ClassID == productClassModel.ParentID).ClassName;
            }
            return View(productClasses.First(m=>m.ClassID == id));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Move(ProductClassModel productClassModel)
        {
            return Json(productClassBLL.MoveClass(productClassModel), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Delete(int id)
        {
            return Json(productClassBLL.Delete<ResultInfo>(id), JsonRequestBehavior.AllowGet);
        }
    }
}

ERP.UI/Views/ProductClass/Create.cshtml
@model ProductClassModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>表单组合</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css" media="all">
</head>
<body>

    <div class="layui-fluid">
        <div class="layui-card">
            <div class="layui-card-header">分类添加</div>
            <div class="layui-card-body" style="padding: 15px;">
                <form class="layui-form" action="" lay-filter="component-form-group">
                    <div class="layui-form-item">
                        <label class="layui-form-label">所属分类</label>
                        <div class="layui-input-block">
                            @Html.Action("Index","ClassList")                            
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">分类名称</label>
                        <div class="layui-input-block">
                            @Html.TextBoxFor(m => m.ClassName,new { lay_verify = "required", placeholder = "请输入",@class="layui-input" })
                        </div>
                    </div>

                    <div class="layui-form-item">
                        <label class="layui-form-label">分类描述</label>
                        <div class="layui-input-block">
                            @Html.TextBoxFor(m => m.ClassIntro, new { lay_verify = "required", placeholder = "请输入", @class = "layui-input" })
                        </div>
                    </div>

                    <div class="layui-form-item layui-layout-admin">
                        <div class="layui-input-block">
                            <div class="layui-footer" style="left: 0;">
                                <button class="layui-btn" lay-submit="" lay-filter="component-form-demo1">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="/layuiadmin/layui/layui.js"></script>
    <script>
      layui.config({
        base: '/layuiadmin/' //静态资源所在路径
      }).extend({
        index: 'lib/index' //主入口模块
      }).use(['index', 'form'], function(){
        var $ = layui.$
        ,admin = layui.admin
        ,element = layui.element
        , form = layui.form;

          

        /* 监听提交 */
        form.on('submit(component-form-demo1)', function(data){
          $.ajax({
              url: "@Url.Action("Create")",
              type: "post",
              dataType: "json",
              data: data.field,
              success: function (d) {
                  layer.msg('添加成功', { icon: 6 }, function () {
                      window.location = "@Url.Action()";
                  });
              }
          })
          return false;
        });
      });
    </script>
</body>
</html>

ERP.UI/Views/ProductClass/Edit.cshtml
@model ProductClassModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>表单组合</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css" media="all">
</head>
<body>

    <div class="layui-fluid">
        <div class="layui-card">
            <div class="layui-card-header">分类修改</div>
            <div class="layui-card-body" style="padding: 15px;">
                <form class="layui-form" action="" lay-filter="component-form-group">
                    <div class="layui-form-item">
                        <label class="layui-form-label">所属分类</label>
                        <div class="layui-input-block">
                            @Html.Action("Index", "ClassList", new { config = new { disabled = "disabled" } })
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">分类名称</label>
                        <div class="layui-input-block">                            
                            @Html.TextBoxFor(m => m.ClassName, new { lay_verify = "required", placeholder = "请输入", @class = "layui-input"})
                        </div>
                    </div>

                    <div class="layui-form-item">
                        <label class="layui-form-label">分类描述</label>
                        <div class="layui-input-block">
                            @Html.TextBoxFor(m => m.ClassIntro, new { lay_verify = "required", placeholder = "请输入", @class = "layui-input" })
                        </div>
                    </div>

                    <div class="layui-form-item layui-layout-admin">
                        <div class="layui-input-block">
                            <div class="layui-footer" style="left: 0;">
                                @Html.HiddenFor(m => m.ClassID)
                                <button class="layui-btn" lay-submit="" lay-filter="component-form-demo1">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="/layuiadmin/layui/layui.js"></script>
    <script>
      layui.config({
        base: '/layuiadmin/' //静态资源所在路径
      }).extend({
        index: 'lib/index' //主入口模块
      }).use(['index', 'form'], function(){
        var admin = layui.admin
        ,element = layui.element
        , form = layui.form;

        /* 监听提交 */
        form.on('submit(component-form-demo1)', function(data){
          $.ajax({
              url: "@Url.Action()",
              type: "post",
              dataType: "json",
              data: data.field,
              success: function (d) {
                  layer.msg('添加成功', { icon: 6 }, function () {
                      window.location = "@Url.Action("Index")";
                  });
              }
          })
          return false;
        });
      });
    </script>
</body>
</html>

ERP.UI/Views/ProductClass/Index.cshtml
@model IEnumerable<ProductClassModel>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>静态表格</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css" media="all">
</head>
<body>
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-header">商品分类</div>
                    <div class="layui-card-body">
                        <table class="layui-table">
                            <colgroup>
                                <col width="150">
                                <col width="200">
                                <col width="200">
                                <col>
                            </colgroup>
                            <thead>
                                <tr>
                                    <th>分类ID</th>
                                    <th>分类名称</th>
                                    <th>分类描述</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.ClassID</td>
                                        <td>
                                            @{ if (item.ParentID == 0)
                                                {
                                                    @Html.Raw($"<b>{item.ClassName}</b>")
                                                }
                                                else
                                                {
                                                    string nbsp = "|";
                                                    for (int i = 0; i < item.Depth * 3; i++)
                                                    {
                                                        nbsp += "-&nbsp;";
                                                    }
                                                    @Html.Raw($"{nbsp}├{item.ClassName}")
                                                }
                                             }
                                        </td>
                                        <td>@item.ClassIntro</td>
                                        <td>
                                            <a class="layui-btn layui-btn-xs" href="@Url.Action("Create", new { id = item.ClassID })"><i class="layui-icon layui-icon-addition"></i>添加</a>
                                            <a class="layui-btn layui-btn-xs layui-btn-normal" href="@Url.Action("Edit", new { id = item.ClassID })"><i class="layui-icon layui-icon-male"></i>修改</a>
                                            <a class="layui-btn layui-btn-xs layui-btn-warm" href="@Url.Action("Move", new { id = item.ClassID })"><i class="layui-icon layui-icon-set-sm"></i>移动</a>
                                            <a class="layui-btn layui-btn-xs layui-btn-danger delete" href="javascript:void(0)" id="@item.ClassID"><i class="layui-icon layui-icon-face-smile"></i>删除</a>
                                        </td>
                                    </tr>
                                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="/layuiadmin/layui/layui.js"></script>
    <script>
  layui.config({
    base: '/layuiadmin/' //静态资源所在路径
  }).extend({
      index: 'lib/index' //主入口模块
  }).use(['index', 'layer'], function () {
      var $ = layui.$;


      $(".delete").click(function () {
          var id = $(this).attr("id");

          layer.confirm('确认删除吗？', function (index) {
              $.ajax({
                  url: "@Url.Action("Delete")",
                  type: "get",
                  dataType: "json",
                  data: {id:id},
                  success: function (d) {
                      layer.msg(d.Msg, {
                          icon: 1,
                          time: 2000 //2秒关闭（如果不配置，默认是3秒）
                      }, function () {
                              if (d.ErrorCode == 0) {
                                  window.location.reload();
                              }
                      });
                  }
              })
          });

      });
  });
    </script>
</body>
</html>

ERP.UI/Views/ProductClass/Move.cshtml
@model ProductClassModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>表单组合</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css" media="all">
</head>
<body>

    <div class="layui-fluid">
        <div class="layui-card">
            <div class="layui-card-header">分类移动</div>
            <div class="layui-card-body" style="padding: 15px;">
                <form class="layui-form" action="" lay-filter="component-form-group">
                    <div class="layui-form-item">
                        <label class="layui-form-label">当前分类</label>
                        <div class="layui-input-block">
                            @Model.ClassName
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">所属分类</label>
                        <div class="layui-input-block">
                            @ViewBag.parentClass
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">目标分类</label>
                        <div class="layui-input-block">
                            @Html.Action("Index", "ClassList", new { config = new { size = "20" } })
                        </div>
                    </div>

                    <div class="layui-form-item layui-layout-admin">
                        <div class="layui-input-block">
                            <div class="layui-footer" style="left: 0;">
                                @Html.HiddenFor(m => m.ClassID)
                                <button class="layui-btn" lay-submit="" lay-filter="component-form-demo1">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="/layuiadmin/layui/layui.js"></script>
    <script>
      layui.config({
        base: '/layuiadmin/' //静态资源所在路径
      }).extend({
        index: 'lib/index' //主入口模块
      }).use(['index', 'form'], function(){
        var admin = layui.admin
        ,element = layui.element
        , form = layui.form;

        /* 监听提交 */
        form.on('submit(component-form-demo1)', function(data){
          $.ajax({
              url: "@Url.Action()",
              type: "post",
              dataType: "json",
              data: data.field,
              success: function (d) {
                  layer.msg('添加成功', { icon: 6 }, function () {
                      window.location = "@Url.Action("Index")";
                  });
              }
          })
          return false;
        });
      });
    </script>
</body>
</html>